### ISSUE TITLE
Add fallback closure to redirect middleware

### ISSUE THREAD

**Issue by asika32764** [middlewares/firewall#16]

**Comment by oscarotero** [comment]
Each middleware is designed to do only one thing.
You can create other middleware to manage 403 responses.

**Comment by asika32764** [comment]
Sorry, this is a mistake, I want to leave message to another firewall repository.

I don't know why I navigate to this repo.

I'll close this issue.

**Comment by asika32764** [comment]
But this is a great firewall middleware, I use this package many times. 👍
