### ISSUE TITLE
Route code still executes even if blacklisted

### ISSUE THREAD

**Issue by mav2287** [middlewares/firewall#3]
It doesn't seem to matter where in the middleware stack I put this if an IP is blacklisted the route is resolved and the code for the route executes. Is there a way to have the code for the route not execute if the route is blacklisted? Just seems like a waste to run the code for the route if the response will be a 403 anyway.

**Comment by oscarotero** [comment]
I don't understand. This middleware should be before any router. You can see [in the code](https://github.com/middlewares/firewall/blob/master/src/Firewall.php#L91) that an error response is returned if the ip is blacklisted.

**Comment by mav2287** [comment]
Sorry maybe it is the terminology I mixed up. Still getting the hang of it. Even though this is before the fastroute and RequestHandler middleware the actual function that the RequestHandler calls still runs. I tested this by putting a die statement inside the a route "/test" and then blacklisting the IP. The result will be that the die() still executes even though the response the user gets in the browser is the 403. My understanding of why it does this is that it sets the 403 as the response, BUT the rest of the middleware stack stills gets ran including the function that the request handler is calling.

**Comment by oscarotero** [comment]
This shouldn't happen. Can you share a code example that reproduce this behavior?

**Comment by mav2287** [comment]
Went back through the code trying to simply something to send and found the issue. I had another custom piece of middleware I made that was using `$handler->handle($request)->getStatusCode()` and it was causing the request handler to still run the handler even though it was a 403. Sorry about that.
