### ISSUE TITLE
m6web/firewall is abandoned

### ISSUE THREAD

**Issue by hschletz** [middlewares/firewall#4]
This package depends on m6web/firewall, which has recently been abandoned.

**Comment by oscarotero** [comment]
Yes, I'm aware. Do you know any good alternative?

**Comment by hschletz** [comment]
I just did a quick search on packagist but found nothing useful for direct filtering. However, there are a lot of libraries for handling IP addresses which can match an address against a network range.

**Comment by oscarotero** [comment]
That could help. Unfortunately, I don't have many free time to update this repository right now. If you're interesting in working on that, feel free to make a pull request.
